### ISSUE TITLE
Ensure consistency in how information is added to API responses 

### ISSUE THREAD

**Issue by Aeilert** [Riksrevisjonen/noAPI#13]
It would helpful  if we make it easier for users to match their input with the resulting response from the API. 

* When querying multiple adresses from _Kartverket_ with `get_address_info()` it is not always clear which addresses found a match if some of the queries fail.

**Comment by ohjakobsen** [comment]
After much thought, my solution is to add a new argument `simplify` to all API functions. The idea behind this argument, is to replicate the behaviour of apply functions, but with a twist. Normally, the user would want a single data.frame to be returned by the function, but in cases where it is important to retrieve an object of equal lengt to the input given to the function, `simplify` can be set to `FALSE` and the function will return a list of values with equal length as the input vector.

**Comment by ohjakobsen** [comment]
`get_address_info()` is a bit of an outlier, as the potential number of arguments that can be set, is quite large. Most of the other functions only handle a single or a handful of arguments, where most or all of the input values are returned with the API response. For `get_address_info()` an additional solution can be to include a concatenated vector of the search parameters as a column in the returned data.frame(s).

**Comment by ohjakobsen** [comment]
@Aeilert: The argument `simplify` has been added to the new API functions for SSB Klass API in #28. The argument should be documented in `get_entity()` when this function is rewritten, and all other functions should then inherit the description with `@inheritParams`.
