### ISSUE TITLE
Confusing warning message 

### ISSUE THREAD

**Issue by Aeilert** [Riksrevisjonen/noAPI#51]
@ohjakobsen: I wonder if the current warning message for `get_entity()` is somewhat confusing, particullary when querying for a specific organisation number. The current message is "No entities found.", while a better message would be to specifically include which number that failed. The message is even more confusing when information on  mulitiple entities is requested. 

E.g.

```r
> df <- get_entity(c('U90099012', '974624532'))
Warning message:
No entities found. 
> head(df)[1]
  organisasjonsnummer
1           974624532
```

**Comment by ohjakobsen** [comment]
Agreed. A message like `No entity found for {x}` would be a good enhancement.
